#development:
#  clients:
#    default:
#      uri: mongodb+srv://abc:1234567890@testdatabase.xeggq.mongodb.net/testDatabase?retryWrites=true&w=majority
#      options:
#        server_selection_timeout: 5